openapi: 3.1.0
info:
  version: 1.0.0
  title: Water tracker app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of waterToday tracker app
tags:
  - name: Auth
    description: Auth operations.
  - name: User
    description: User operations.
  - name: Water
    description: Water operations.
servers:
  - url: https://projectwatertrackerteam4.onrender.com
paths:
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/register/post.yaml'
  /auth/verify:
    get:
      $ref: '../swagger/paths/auth/verify/get.yaml'
  /auth/login:
    post:
      $ref: '../swagger/paths/auth/login/post.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout/post.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refresh/post.yaml'
  /auth/send-reset-email:
    post:
      $ref: '../swagger/paths/auth/send-reset-email/post.yaml'
  /auth/reset-pwd:
    post:
      $ref: '../swagger/paths/auth/reset-pwd/post.yaml'
  /auth/get-oauth-url:
    get:
      $ref: '../swagger/paths/auth/get-oauth-url/get.yaml'
  /users/current:
    get:
      $ref: '../swagger/paths/users/current/get.yaml'
  /users:
    patch:
      $ref: '../swagger/paths/users/patch.yaml'
  /users/avatar:
    patch:
      $ref: '../swagger/paths/users/avatar/patch.yaml'
  /water/day/{date}:
    get:
      $ref: '../swagger/paths/water/{date}/get.yaml'
  /water:
    post:
      $ref: '../swagger/paths/water/post.yaml'
  /water/{id}:
    patch:
      $ref: '../swagger/paths/water/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/water/{id}/delete.yaml'
  /water/{month}/{year}:
    get:
      $ref: '../swagger/paths/water/water-by-month/get.yaml'
  /userNormaHistory:
    put:
      $ref: '../swagger/paths/userNormaHistory/put.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
